---
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
os: linux
dist: xenial
env:
  global:
    - DEPS_DIR=$HOME/dependencies
  matrix:
    - WITH_TA_LIBRARY=yes
      TA_INCLUDE_PATH=$DEPS_DIR/include
      LD_LIBRARY_PATH=$DEPS_DIR/lib
      TA_LIBRARY_PATH=$DEPS_DIR/lib
cache:
  directories:
    - $DEPS_DIR
install:
  - pip install --upgrade pip wheel
  - pip install -r requirements_test.txt
  - if [ $WITH_TA_LIBRARY = "yes" ]; then
      ./tools/build_talib_from_source.bash $DEPS_DIR;
    fi
script:
  - make test
