[project]
name = "ta-lib"
version = "0.4.33"
dynamic = ["authors", "classifiers", "dependencies", "description", "license", "readme"]

[build-system]
requires = ["setuptools >= 51.0.0", "wheel", "numpy<2.0.0"]
build-backend = "setuptools.build_meta:__legacy__"
